### ISSUE TITLE
Needs README.md

### ISSUE THREAD

**Issue by adwaitrawat** [adwaitrawat/N-Body-Simulation#1]
would be better if someone wrote a readme file for the project

**Comment by Sweta271097** [comment]
@adwaitrawat Can I take up this issue?

**Comment by adwaitrawat** [comment]
go crazy

**Comment by Sweta271097** [comment]
@adwaitrawat Can I know a little bit more about what N-Body-Simulation is all about?

**Comment by adwaitrawat** [comment]
it's a project aimed to simulate motion of celestial bodies in free space. The project aims to use OpenGL for graphics and is in testing phase.

**Comment by adwaitrawat** [comment]
building commands are
```
meson build
ninja -C build
./build/src/n-body
```

though it would be better if one is using flatpak builder or gnome-builder
